### ISSUE TITLE
PDF文件的下载

### ISSUE THREAD

**Issue by shangfcSean** [xhnbzdl/feishu-doc-export#11]
非常感谢，这么软件太棒了，不但功能很强大，而且文档很齐全，提示也很到位。不过我的知识库里有很多PDF和图片，可惜这个软件不支持下载，请问有没有可能增加上这个功能？

**Comment by xhnbzdl** [comment]
@shangfcSean 你指的是，导出pdf的时候，数量多了的情况下会包400的问题吗

**Comment by xhnbzdl** [comment]
已修复，最新版本：[0.0.4](https://github.com/xhnbzdl/feishu-doc-export/releases/tag/0.0.4)
