### ISSUE TITLE
【ERROR】没有可支持导出的知识库！！！（请按任意键退出！）

### ISSUE THREAD

**Issue by miniluphy** [xhnbzdl/feishu-doc-export#15]
首先非常感谢这个一键导出的工具，简直太棒了。不过目前遇到了点问题：
最新版本0.0.3，按照操作设置了云文档权限，以及群聊机器人等等，win平台运行后报错：【ERROR】没有可支持导出的知识库！！！（请按任意键退出！）
想请教一下是哪里出了问题，谢谢您啦~~ 再次感谢~~

**Comment by xhnbzdl** [comment]
加下qq：2804184253

**Comment by xhnbzdl** [comment]
已支持解决

**Comment by miniluphy** [comment]
已解决，是因为没有给群聊添加管理员权限，给群聊添加完管理员权限就可以读取了：
之前一直不知道怎么给群聊增加管理员权限，原来检索一下就好了
***********
![image](https://github.com/xhnbzdl/feishu-doc-export/assets/68535103/e549208e-c4ca-4328-b84e-be2014e35f5c)
**********
![image](https://github.com/xhnbzdl/feishu-doc-export/assets/68535103/7f02a446-ddcc-491f-8287-f1b64409411b)
**********
非常感谢开发者！！！

**Comment by snowman** [comment]
我的天啊, 非常感谢, 你必须输入群聊名称才会显示出来!
