### ISSUE TITLE
Bug - 导出为PDF文件时出错

### ISSUE THREAD

**Issue by erbanku** [xhnbzdl/feishu-doc-export#19]
您好，这款工具非常实用，Markdown和Docx导出都毫无问题。然而在导出为PDF文件时，经常出现问题使得下载不完整。能否劳烦您帮忙查看一下是何原因造成的呢？谢谢。
## 出错截图
```
【ERROR】请求异常！！！请检查您的网络环境。异常信息：服务器响应了错误的http状态码：400 Bad Request（请按任意键退出！）
```
![image](https://github.com/xhnbzdl/feishu-doc-export/assets/79493862/2cc0076b-d99c-4fc5-b706-a531e3b771f3)

**Comment by erbanku** [comment]
导出10来个文件后就会出错

**Comment by xhnbzdl** [comment]
> 导出10来个文件后就会出错

qq:2804184253，加下qq我详细了解一下

**Comment by xhnbzdl** [comment]
已更新到[0.0.4](https://github.com/xhnbzdl/feishu-doc-export/releases/tag/0.0.4)
