### ISSUE TITLE
导出云空间文档时候无法下载异常

### ISSUE THREAD

**Issue by jianghuzuike** [xhnbzdl/feishu-doc-export#20]
【ERROR】请求异常！！！异常信息：服务器响应了错误的http状态码：400 Bad Request，堆栈信息：   at WebApiClientCore.Implementations.DefaultApiActionInvoker`1.InvokeAsync(HttpClientContext context, Object[] arguments)
   at feishu_doc_export.HttpApi.FeiShuHttpApiCaller.GetFolderMeta(String folderToken)（请按任意键退出！）
大佬有空帮忙看看什么情况

**Comment by xhnbzdl** [comment]
> 【ERROR】请求异常！！！异常信息：服务器响应了错误的http状态码：400 Bad Request，堆栈信息： at WebApiClientCore.Implementations.DefaultApiActionInvoker`1.InvokeAsync(HttpClientContext context, Object[] arguments) at feishu_doc_export.HttpApi.FeiShuHttpApiCaller.GetFolderMeta(String folderToken)（请按任意键退出！） 大佬有空帮忙看看什么情况

2804184253加下qq

**Comment by jianghuzuike** [comment]
问题解决了是没有设置飞书的权限，需要开通文档权限
