### ISSUE TITLE
知识库中文件很多，大概下载到1900个文件的时候报错

### ISSUE THREAD

**Issue by feixia111** [xhnbzdl/feishu-doc-export#32]
**报错信息如下**：【ERROR】请求异常！！！异常信息： 服务器响应了错误的http状态码：500 Internal Server Error，堆栈信息：    at WebApiClientCore.Implementations.DefaultApiActionInvoker`1.InvokeAsync(HttpClientContext context, Object[] arguments)

出现上述报错信息后，就会提示“请按任意键退出”， 点击后就退出了。  
建议： 这里是否可以增加单个文件上传失败的跳过机制，继续下载其他文件呢？ （因为自己的知识库文档比较多，大概有2万-3万，中间失败后，又要重新下载）

**Comment by feixia111** [comment]
自己分析原因可能是： 网络问题，或者是飞书本身有限制（飞书 API 有总每分钟 100 次请求）
重试后导出成功。  （自己的这个知识库文件个数总共有1万多个）

**Comment by xhnbzdl** [comment]
> 自己分析原因可能是： 网络问题，或者是飞书本身有限制（飞书 API 有总每分钟 100 次请求） 重试后导出成功。 （自己的这个知识库文件个数总共有1万多个）

你说的对的，两者都有可能，你上面说的意见确实可以加一下，不过最近很忙，不知道什么时候有空再来测试这个

**Comment by xhnbzdl** [comment]
已在[0.0.4.1](https://github.com/xhnbzdl/feishu-doc-export/releases/tag/0.0.4.1)中进行优化，下载失败后跳过。
