### ISSUE TITLE
程序执行完之后直接退出的需求

### ISSUE THREAD

**Issue by murphyzhao** [xhnbzdl/feishu-doc-export#33]
现在程序执行完成后，显示“请按任意键退出”。
因为我是后台定期执行，想要程序执行完成后自动退出，而不是还要按键。
期待可以增加一个退出参数。

**Comment by xhnbzdl** [comment]
> 现在程序执行完成后，显示“请按任意键退出”。 因为我是后台定期执行，想要程序执行完成后自动退出，而不是还要按键。 期待可以增加一个退出参数。

已增加参数`--quit`，https://github.com/xhnbzdl/feishu-doc-export/releases/tag/0.0.4.1
