### ISSUE TITLE
spaceId error

### ISSUE THREAD

**Issue by chunbaisikio** [xhnbzdl/feishu-doc-export#34]
1、我的实际需求是通过脚本定期同步数据，问一下是否存在接口可以直接获取当前知识库下的所有文件名称【或者是token】
2、在通过当前项目下载知识库的时候，尝试使用spaceId进行直接自动化下载知识库，但是出现报错
![QQ截图20240627142214](https://github.com/xhnbzdl/feishu-doc-export/assets/37649051/af86c336-584b-41e4-a1e2-43c6dd488412)

**Comment by xhnbzdl** [comment]
> 1、我的实际需求是通过脚本定期同步数据，问一下是否存在接口可以直接获取当前知识库下的所有文件名称【或者是token】 2、在通过当前项目下载知识库的时候，尝试使用spaceId进行直接自动化下载知识库，但是出现报错 ![QQ截图20240627142214](https://private-user-images.githubusercontent.com/37649051/343654651-af86c336-584b-41e4-a1e2-43c6dd488412.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MDQ4NTYsIm5iZiI6MTcyMDQwNDU1NiwicGF0aCI6Ii8zNzY0OTA1MS8zNDM2NTQ2NTEtYWY4NmMzMzYtNTg0Yi00MWU0LWExZTItNDNjNmRkNDg4NDEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDAyMDkxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4MTdlMjc4MjM0MDc4MjYyN2M5ZTM2MDUyNWU4ZWI2ZmE2ODQ5YmE5MDdmN2ExMjExZDA2N2ExNDc4NDRhMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.69_6F2A_C1kt38BYkqVERgyR2CzLmleTPHxwgNLbV8w)

报错尝试重试后任然出现吗？可能是权限没满足，可以加q看看：2804184253

**Comment by chunbaisikio** [comment]
感谢作者解惑，实际是spaceId需要另外去获取。
